### ISSUE TITLE
Can I query the weather for my current position?

### ISSUE THREAD

**Issue by strukturart** [user18130814200115-2/User-s-Weather#2]
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

**Comment by user18130814200115-2** [comment]
The entire back end of the application is handled by wttr.in. It automatically determines the closest dadapoint to you (by IP), this is what is loaded when the app first starts. When the app is loaded you can input and location (city, region, etc.) And wttr.in will take the closest location to the desired one.


If nessecary, I will look into using the geolocation api to determine the starting location.

For more information on the backend check https://github.com/chubin/wttr.in

I hope I answered your question

**Comment by strukturart** [comment]
what do you think of first querying the geolocation and then querying the next town. I do it like this in my app: 
https://github.com/strukturart/qlauncher/blob/0b12ccfbaa71edb219f721af7be43acd9638d377/application/assets/js/script.js#L434

**Comment by user18130814200115-2** [comment]
I will have a look at this soon, it seems like a good idea. Though I am still wondering whether it enhances the user experience.

**Comment by user18130814200115-2** [comment]
I have thought long and hard about this question and I came to a conclusion.
Currently, the location finding is outsourced to a server, thus reducing the strain on the device. Using the devices GPS and other available methods COULD improve accuracy. Since wttr.in only has a limited number of data-points, the accuracy does not seem all that important to me. 
However! I will make a version of the app that utilises mozilla's Geo-location API though this feature will stay separate from the master branch for now

**Comment by user18130814200115-2** [comment]
There is now source code as well as binaries available for a Geolocation version of the app
